services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=latte
      - DB_PASSWORD=latte
      - DB_NAME=frappuccino
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=frappuccino
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U latte" ]
      interval: 3s
      timeout: 5s
      retries: 10 # Если база данных заработает после всех retries, контейнер не вернется в healthy автоматически!
