services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=latte
      - DB_PASSWORD=latte
      - DB_NAME=frappuccino
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
  db:
    ports:
      - 5432:5432
    image: postgres:alpine
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=frappuccino
    volumes:
      - ./db/1_inventory.sql:/docker-entrypoint-initdb.d/1_inventory.sql
      - ./db/2_menu.sql:/docker-entrypoint-initdb.d/2_menu.sql
      - ./db/3_order.sql:/docker-entrypoint-initdb.d/3_order.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U latte -d frappuccino" ]
      # test: [ "CMD-SHELL", "pg_isready -h someremotehost" ]
      # test: [ "CMD-SHELL", "pg_isready -h someremotehost -p 5432 -U latte -d frappuccino" ]
      interval: 3s
      timeout: 5s
      retries: 10 # Если база данных заработает после всех retries, контейнер не вернется в healthy автоматически!
